version: 2

sources:
  - name: raw_data                # name of the source
    schema: raw_data              # real schema name in the database
    tables:
      - name: posts               # name of the table created by dlt